# -*- coding: utf-8 -*-
"""DATASERIESpractice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yramVOvA5tB_XU0tftdvi99A9X49_Y28

---

**DATA SERIES** **PRACTICE**

***PANDAS SERIES*** :
"""

from pandas import Series as pd

import numpy as np

"""creating a simple series :"""

ser=pd([1,2,3,4])
print(ser)

"""getting values in the series ser"""

ser.values

"""getting index of series ser"""

ser.index

"""creating a series with data lables"""

ser2=pd([2,4,6,8],index=['a','b','c','d'])
print(ser2)
print(ser2.index)

"""retriving data values using lables in index"""

print("first data value :")
print(ser2['a'])
print("last data value :")
print(ser2['d'])

"""assigning data values using lables in index"""

ser2['b']=40
ser2['c']=60
print(ser2)

"""we can print in desired order"""

ser2[['d','a','c','b']]

"""using numpy functions:

a)filtering with boolean array
"""

ser2[ser2>20]

"""b)scalar multiplication"""

ser2*4

"""c)applying math functions"""

np.exp(ser2)

"""checking index availability"""

'e' in ser2

'b' in ser2

"""creating series by passing dictionary"""

mydic = {'cycle': 10, 'bike': 80, 'train':200 , 'jet':1000}
ser3=pd(mydic)
print(ser3)

"""passing mydic keys in the order i want to appear"""

myind=['jet','bike','car','train','cycle']
ser4=pd(mydic,index=myind)
print(ser4)

"""functions to detect the missing data in series

1)isnull()
"""

pd.isnull(ser4)

"""2)notnull()"""

ser4.notnull()

"""alignment in series by index lables"""

print(ser3)
print(ser4)

ser3+ser4

"""naming"""

ser4.name='speed(kmph)'
ser4.index.name='vehicle'
print(ser4)

"""altering indexes"""

ser4.index=['plane','auto','bus','ship','cart']
print(ser4)